name: Enable Auto Merge

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: write

jobs:
  enable-auto-merge:
    name: Enable Auto Merge
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    steps:
      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh pr merge "$PR_NUMBER" \
            --repo "$GH_REPO" \
            --auto \
            --squash
